name: Run CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - '*.js'
      - '*.json'
  workflow_dispatch:

jobs:
  run_ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
